apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flaskapp-pvc
  namespace: homer-wp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default