apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  namespace: homer-wp
spec:
  type: LoadBalancer
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000