- name: Crear Secret para ACR (type=dockerconfigjson)
  kubernetes.core.k8s:
    state: present
    namespace: homer-wp
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: acr-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ {
          'auths': {
            acr_login_server: {
              'username': acr_username,
              'password': acr_password,
              'auth': (acr_username ~ ':' ~ acr_password) | b64encode
            }
          }
        } | to_nice_json | b64encode }}"